= GameIn

Game in is a social platform where gamers can meet and enjoy their gaming sessions at the fullest.

== Our idea
Imagine you want to play something after a long school or work day and you don't have any idea with whom you should play cause your friends are busy or you don't have any.

Here is where we come in action. We want to develop a platform where gamers can create online parties and those who are searching for parties can see them in a feed.

Aside from that we want to implement different party functionalities like tournament mode to make sure you have fun on our platform or a premium function where you can customize your account to show your friends how cool you are or to define your personality.

= Our goal

We want to make gaming and online socializing easier and funnier than ever. We also want to support people who want to start a career in e-sports as server owners and average gamers.

= Project Members

Stana Andrei - Backend, Functionability, System planning
-
Kyaw Htet Htun - Mostly Frontend, Fullstack, Responsive design
