= GameIn

Game in is a social platform where gamers can meet and enjoy their gaming sessions at the fullest.

== Our idea
Imagine you want to play something after a long school or work day and you don't have any idea with whom you should play cause your friends are busy or you don't have any.

Here is where we come in action. We want to develop a platform where gamers can create online parties and those who are searching for parties can see them in a feed.

Aside from that we want to implement different party functionalities like tournament mode to make sure you have fun on our platform or a premium function where you can customize your account to show your friends how cool you are or to define your personality.

= Our goal

We want to make gaming and online socializing easier and funnier than ever. We also want to support people who want to start a career in e-sports as server owners and average gamers.

= Website Structure

We will have a log in / register part if you're not already registered or logged in. If you're logged in you will see a feed where parties are displayed with the language the people are speaking in those parties and the game they're currently playing. There will be game feeds too where you can post everything about your favourite game and debate it.

You'll be able if you pay our premium version monthly to customize your account.

= Technologies we want to use

*HTML, CSS, Typescript, Svelte, MariaDB, JWT, Websockets, NodeJS*

= Tasks
* Frontend first semester
. Index start site till November
. Background animationen
. About us site till november
. Explaining our Goal on another site till december

= Risks and Migration strategies

The biggest risk will be the lack of time, but we plan to remove some ideas and improve the simpler ones to complement them.
Another risk will be that the idea won't seem good enough. We want to make it cool by making a good presentation for it and designing an eye catching UI.
The knowledge of different technologies will be a small problem but if we don't know how to do something we can replace that technology or ask an expert.

= Project Members

Stana Andrei - Backend, Functionability, System planning

Kyaw Htet Htun - Mostly Frontend, Fullstack, Responsive design
